[phases.setup]
nixPkgs = ["php", "phpPackages.composer", "apacheHttpd"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader"
]

[start]
cmd = "vendor/bin/heroku-php-apache2 public/"
